main:
    - nicfit.py

#extra_example:
#    - pkg
#    - pkg2

test:
    - pytest
    - pytest-cov
    - pytest-runner
    {%- if cookiecutter.pyapp_type == "asyncio" %}
    - pytest-asyncio
    {%- endif %}

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    {%- if cookiecutter.gettext_domain != "None" %}
    - babel
    {%- endif %}
    - check-manifest
    - flake8
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    {%- if cookiecutter.use_paver == "yes" %}
    - paver
    - cogapp
    - sphinxcontrib-paverutils
    {%- endif %}
    - pyaml
    - pss
    - git+https://github.com/nicfit/gitchangelog.git
