main:

#extra_example:
#    - pkg
#    - pkg2

test:
    - pytest
    - pytest-cov
    - pytest-runner

dev:
    - Sphinx
    {%- if cookiecutter.gettext_domain != "None" %}
    - babel
    {%- endif %}
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    {%- if cookiecutter.use_paver == "yes" %}
    - paver
    - cogapp
    - sphinxcontrib-paverutils
    {%- endif %}
    - pyaml
