main:
    - deprecation
    - attrs
    - PyYaml

extra_cookiecutter:
    - cookiecutter

extra_curio:
    - curio

extra_shell:
    - prompt-toolkit
    - pygments

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-asyncio
    - pytest-curio
    - babel

dev:
    - Sphinx
    - sphinx_rtd_theme
    - babel
    - check-manifest
    - flake8
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    - pss
    - git+https://github.com/nicfit/gitchangelog.git
