main:
    - deprecation
    - attrs
    - pyaml

extra_cookiecutter:
    - cookiecutter

extra_curio:
    - curio

extra_prompt:
    - prompt_toolkit

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-asyncio
    - pytest-curio
    - babel

dev:
    - Sphinx
    - sphinx_rtd_theme
    - babel
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    - pyaml
    - pss
